# Generated by Django 5.0.1 on 2024-01-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_cliente_cnpj_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
