# Generated by Django 5.0.1 on 2024-01-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_unidade_produto_unidade'),
        ('vendas', '0003_alter_venda_quantidade_alter_venda_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(to='produtos.produto'),
        ),
    ]
