# Generated by Django 5.0.1 on 2024-01-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_remove_venda_comprador_remove_venda_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
