# Generated by Django 5.0.1 on 2024-01-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_alter_itemvenda_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
